### ISSUE TITLE
AppImage for download

### ISSUE THREAD

**Issue by probonopd** [MovieCast/desktop#16]
https://github.com/MovieCast/moviecast-desktop/blob/289a352e597ce48267aa429ffae8868acb22c5e3/package.json#L58

Please upload an AppImage to the project's GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by paulhobbel** [comment]
Thanks for the tip. In future releases the AppImage will be included in the releases.
I never knew were these AppImages were useful for, but now I know.

**Comment by paulhobbel** [comment]
@probonopd Does this version work? I currently don't have a Linux env in my area:
https://153-74919122-gh.circle-artifacts.com/0/home/circleci/moviecast-desktop/release/moviecast-desktop-0.0.1-alpha.4-x86_64.AppImage

**Comment by probonopd** [comment]
Yes it does, thank you.

**Comment by paulhobbel** [comment]
Nice, yet to test it myself

**Comment by probonopd** [comment]
Would be nice if you could provide this on GitHub Releases, then I could add it to the AppImageHub central directory of available AppImages. Thanks.

**Comment by paulhobbel** [comment]
Oh yes my bad, seems like I forgot to setup the Linux build server correctly since it also didn't upload the .Deb file

**Comment by probonopd** [comment]
So there is an AppImage for an older build but not for the latest. It would be great if it could be added, thank you.

**Comment by paulhobbel** [comment]
Yea beta 2 will be released tomorrow, will include the App image for that one

**Comment by paulhobbel** [comment]
I added the AppImage binary

**Comment by probonopd** [comment]
Thank you.

What is it trying to do here?

```
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 4 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 3 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 2 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 1 more times
Failed to fetch extension, trying 0 more times
Error: net::ERR_INTERNET_DISCONNECTED
Failed to fetch extension, trying 0 more times
```

This is when running without Internet access.

**Comment by paulhobbel** [comment]
It tries to add some developer extensions to debug if needed

**Comment by probonopd** [comment]
Can you make it launch properly when there is no internet connectivity? Thanks.

**Comment by paulhobbel** [comment]
We are currently rewriting MovieCast Desktop as a whole. This issue no longer exists in v0.2.0

**Comment by paulhobbel** [comment]
Hi @probonopd I've pushed one final update for v0.1 this also includes an fix for the issue without internet connectivity. Hope it helps you

**Comment by probonopd** [comment]
Thank you very much. Please let me know once 0.2.0 is available. Right now we are still getting this:

https://travis-ci.org/AppImage/appimage.github.io/builds/406716503#L559

**Comment by paulhobbel** [comment]
Oh that's a different error though. Will look tomorrow that's seems to be an issue in the updater of MovieCast, needs to be disabled in AppImage anyways. Does AppImage set some sort of env variable I can check to see if it runs from an AppImage?

**Comment by probonopd** [comment]
`$APPIMAGE` and `$APPDIR` are set and non-empty
